name: Deploy Discord Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "DEEPSEEKAPI=${{ secrets.DEEPSEEKAPI }}" >> .env
        echo "DISCORDAPPID=${{ secrets.DISCORDAPPID }}" >> .env
        echo "TOKEN=${{ secrets.TOKEN }}" >> .env

    - name: Register Commands
      run: npm run register
      env:
        DEEPSEEKAPI: ${{ secrets.DEEPSEEKAPI }}
        DISCORDAPPID: ${{ secrets.DISCORDAPPID }}
        TOKEN: ${{ secrets.TOKEN }}

    - name: Start Bot
      run: npm start
      env:
        DEEPSEEKAPI: ${{ secrets.DEEPSEEKAPI }}
        DISCORDAPPID: ${{ secrets.DISCORDAPPID }}
        TOKEN: ${{ secrets.TOKEN }}
